# Generated by Django 6.0.2 on 2026-02-12 04:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VendorSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme_name', models.CharField(choices=[('classic', 'Classic'), ('sunrise', 'Sunrise'), ('forest', 'Forest'), ('ocean', 'Ocean')], default='classic', max_length=40)),
                ('primary_color', models.CharField(default='#1B4D3E', max_length=7)),
                ('secondary_color', models.CharField(default='#F4A259', max_length=7)),
                ('background_color', models.CharField(default='#F5F7F4', max_length=7)),
                ('text_color', models.CharField(default='#1C1C1C', max_length=7)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='vendorapp.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='VendorStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('staff', 'Staff User'), ('manager', 'Manager')], default='staff', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_memberships', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='vendorapp.vendor')),
            ],
            options={
                'ordering': ['vendor__name', 'user__username'],
                'unique_together': {('vendor', 'user')},
            },
        ),
    ]
