# Generated by Django 6.0.2 on 2026-02-12 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorapp', '0003_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorsettings',
            name='vendor_logo',
            field=models.ImageField(blank=True, null=True, upload_to='vendors/logos/'),
        ),
    ]
