# Generated by Django 6.0.2 on 2026-02-12 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorapp', '0004_vendorsettings_vendor_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='currency_code',
            field=models.CharField(choices=[('$', '$'), ('KWD', 'KWD'), ('AEU', 'AEU')], default='$', max_length=3),
        ),
    ]
