# Generated by Django 6.0.2 on 2026-02-12 08:17

import django.core.validators
from django.db import migrations, models


def normalize_vendor_currency_codes(apps, schema_editor):
    Vendor = apps.get_model("vendorapp", "Vendor")
    for vendor in Vendor.objects.all().only("id", "currency_code"):
        code = (vendor.currency_code or "").strip().upper()
        if code == "$":
            code = "USD"
        elif code == "AEU":
            code = "AED"
        if len(code) != 3 or not code.isalpha():
            code = "USD"
        if vendor.currency_code != code:
            vendor.currency_code = code
            vendor.save(update_fields=["currency_code"])


class Migration(migrations.Migration):

    dependencies = [
        ('vendorapp', '0005_vendor_currency_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='currency_code',
            field=models.CharField(default='USD', max_length=3, validators=[django.core.validators.RegexValidator('^[A-Z]{3}$', 'Currency must be a 3-letter ISO code (e.g. USD).')]),
        ),
        migrations.RunPython(normalize_vendor_currency_codes, migrations.RunPython.noop),
    ]
