# Generated by Django 6.0.2 on 2026-02-12 13:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorapp', '0007_packageinvoice_stockmovement_supportticket_auditlog_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffpermission',
            name='module',
            field=models.CharField(choices=[('products', 'Products'), ('offers', 'Offers'), ('orders', 'Orders'), ('staff', 'Staff'), ('packages', 'Packages'), ('settings', 'Settings'), ('analytics', 'Analytics')], max_length=30),
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('offer_type', models.CharField(choices=[('product', 'Single Product'), ('collection', 'Collection')], default='product', max_length=20)),
                ('discount_type', models.CharField(choices=[('percent', 'Percent (%)'), ('fixed', 'Fixed Amount')], default='percent', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('products', models.ManyToManyField(blank=True, related_name='offers', to='vendorapp.product')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='vendorapp.vendor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
