# Generated by Django 6.0.2 on 2026-02-12 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorapp', '0010_heroslide'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorsettings',
            name='facebook_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='vendorsettings',
            name='instagram_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='vendorsettings',
            name='tiktok_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='vendorsettings',
            name='x_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='vendorsettings',
            name='youtube_url',
            field=models.URLField(blank=True),
        ),
    ]
