from django.urls import path

from . import views

app_name = "vendorapp"

urlpatterns = [
    path("", views.dashboard, name="dashboard"),
    path("analytics/", views.analytics_dashboard, name="analytics"),
    path("audit-logs/", views.audit_log_list, name="audit-log-list"),
    path("packages/", views.package_list, name="package-list"),
    path("packages/create/", views.package_create, name="package-create"),
    path("packages/<str:token>/edit/", views.package_update, name="package-update"),
    path("invoices/", views.invoice_list, name="invoice-list"),
    path("invoices/create/", views.invoice_create, name="invoice-create"),
    path("invoices/<str:token>/toggle-paid/", views.invoice_toggle_paid, name="invoice-toggle-paid"),
    path("products/", views.product_list, name="product-list"),
    path("products/bulk/", views.product_bulk_action, name="product-bulk"),
    path("products/export/", views.product_export_csv, name="product-export"),
    path("products/create/", views.product_create, name="product-create"),
    path("products/<str:token>/stock/", views.product_stock_adjust, name="product-stock-adjust"),
    path("products/<str:token>/edit/", views.product_update, name="product-update"),
    path("products/<str:token>/delete/", views.product_delete, name="product-delete"),
    path("offers/", views.offer_list, name="offer-list"),
    path("offers/create/", views.offer_create, name="offer-create"),
    path("offers/<str:token>/edit/", views.offer_update, name="offer-update"),
    path("offers/<str:token>/toggle/", views.offer_toggle_active, name="offer-toggle"),
    path("reviews/", views.review_list, name="review-list"),
    path("reviews/<str:token>/delete/", views.review_delete, name="review-delete"),
    path("hero-slides/", views.hero_slide_list, name="hero-slide-list"),
    path("hero-slides/create/", views.hero_slide_create, name="hero-slide-create"),
    path("hero-slides/<str:token>/edit/", views.hero_slide_update, name="hero-slide-update"),
    path("hero-slides/<str:token>/toggle/", views.hero_slide_toggle_active, name="hero-slide-toggle"),
    path("hero-slides/<str:token>/delete/", views.hero_slide_delete, name="hero-slide-delete"),
    path("orders/export/", views.order_export_csv, name="order-export"),
    path("categories/", views.category_list, name="category-list"),
    path("categories/create/", views.category_create, name="category-create"),
    path("categories/<str:token>/edit/", views.category_update, name="category-update"),
    path("categories/<str:token>/delete/", views.category_delete, name="category-delete"),
    path("staff/", views.staff_list, name="staff-list"),
    path("staff/create/", views.staff_create, name="staff-create"),
    path("staff/superadmin-create/", views.superadmin_vendor_user_create, name="superadmin-vendor-user-create"),
    path("staff/<str:token>/toggle/", views.staff_toggle_active, name="staff-toggle"),
    path("invites/", views.invite_list, name="invite-list"),
    path("invites/create/", views.invite_create, name="invite-create"),
    path("permissions/", views.permissions_matrix, name="permissions"),
    path("tickets/", views.ticket_list, name="ticket-list"),
    path("tickets/create/", views.ticket_create, name="ticket-create"),
    path("tickets/<str:token>/edit/", views.ticket_update, name="ticket-update"),
    path("saved-filters/", views.saved_filter_list, name="saved-filter-list"),
    path("saved-filters/create/", views.saved_filter_create, name="saved-filter-create"),
    path("saved-filters/<str:token>/apply/", views.saved_filter_apply, name="saved-filter-apply"),
    path("saved-filters/<str:token>/delete/", views.saved_filter_delete, name="saved-filter-delete"),
    path("settings/", views.vendor_theme_settings, name="settings"),
]
