# Generated by Django 6.0.2 on 2026-02-12 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketapp', '0003_product_category'),
        ('vendorapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='vendorapp.vendor')),
            ],
            options={
                'ordering': ['vendor__name', 'name'],
                'unique_together': {('vendor', 'name')},
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='marketapp.vendorcategory'),
        ),
    ]
